version: '3.7'
services:
  postgres-db:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      # - "./data:/var/lib/postgresql/learn/data" # volume is mounted to a Windows file system directory (/mnt/)
      - "~/pgdata:/var/lib/postgresql/data:Z" # best-practice: volume is mounted to a linux directory
    healthcheck:
      test: [ "CMD", "pg_isready", "-U" ]
      interval: 5s
      retries: 5
    restart: always

  # provide UI for postgres
  postgres-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "8080:80"

  # provide jupyter 
  jupyter-nb:
    image: jupyter/minimal-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter:/home/jovyan/work
